### ISSUE TITLE
include_all issue

### ISSUE THREAD

**Issue by ccastaneda1218** [sinanerdinc/robotframework-testrail#2]
Hello,

I changed the "include_all": **False** in robot_testrail.py, and I'm getting the below error. Please provide some guidance on how to fix this issue. I would greatly appreciate it.

`Traceback (most recent call last):
  File "/usr/src/project/robot_testrail.py", line 77, in <module>
    run()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/project/robot_testrail.py", line 73, in run
    _testrail.add_result_for_case(report_file, run_info)
  File "/usr/src/project/robot_testrail.py", line 56, in add_result_for_case
    resp = self.client.send_post('add_result_for_case/' + str(run_info['id']) + '/' + str(cid), payload)
  File "/usr/src/project/testrail.py", line 48, in send_post
    return self.__send_request('POST', uri, data)
  File "/usr/src/project/testrail.py", line 82, in __send_request
    raise APIError('TestRail API returned HTTP %s (%s)' % (e.code, error))
testrail.APIError: TestRail API returned HTTP 400 ("No (active) test found for the run/case combination.")`

**Comment by sinanerdinc** [comment]
Hi @ccastaneda1218 
If you set include_all as False, you have to send case_ids parameters to testrailApi, but this feature is not impemented yet.

**Comment by sinanerdinc** [comment]
i am working on it.
